#!/bin/bash

COMMIT_MSG_FILE=$1

# Get the GPT API Key as an environment variable
OPENAI_API_KEY=$(echo $OPENAI_API_KEY)
if [ -z "$OPENAI_API_KEY" ]; then
  echo "GPT API key is required"
  exit 1
fi

# Call the aigitmsg binary with the GPT API Key as an argument
aigitmsg --gpt-key "$OPENAI_API_KEY" > "$COMMIT_MSG_FILE"
