#!/bin/sh

# Load the user's profile if found, supporting common shells
if [ -f ~/.bash_profile ]; then
  . ~/.bash_profile
elif [ -f ~/.bashrc ]; then
  . ~/.bashrc
elif [ -f ~/.zshrc ]; then
  . ~/.zshrc
elif [ -f ~/.profile ]; then
  . ~/.profile
fi

# load the user's environment variables if found
if [ -f ~/.bash_env ]; then
  . ~/.bash_env
elif [ -f ~/.zshenv ]; then
  . ~/.zshenv
fi

COMMIT_MSG_FILE=$1

# Get the GPT API Key as an environment variable
OPENAI_API_KEY=$(echo $OPENAI_API_KEY)
if [ -z "$OPENAI_API_KEY" ]; then
  echo "GPT API key is required"
  exit 1
fi

# Call the aigitmsg binary with the GPT API Key as an argument
aigitmsg --gpt-key "$OPENAI_API_KEY" --context-lines 5 --commit-msg-path "$COMMIT_MSG_FILE" > "$COMMIT_MSG_FILE"

# Open the file in the configured editor for review
${EDITOR:-nano} "$COMMIT_MSG_FILE"
